### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by Sanyyouisf**

### CODE REVIEW

**Comment by Sanyyouisf** [comment]
finish

**Comment by Sanyyouisf** [comment]
@ostrander-nathan

**Comment by morecallan** [comment]
Looking good, @Sanyyouisf! 
My only comment is that you should comment your code for readability, you do a great job of it in your CSS, but maybe you could add the project specs to the html (where it is applicable).

You also have a directory inside of the directory, we should get that removed before you merge the project. 

You also want to have more commits next time. (Commit for each feature). 

Looks good! Just a few changes before we are ready to merge:)

**Comment by rousell** [comment]
@Sanyyouisf Please make sure to address callan's suggestions. Once you've done so, I can confirm that you've completed the quiz and complete the PR. Thank you!

**Comment by Sanyyouisf** [comment]
@Lauren Rouse
finish

**Comment by morecallan** [comment]
👍  very nice!

**Pull request merged**
